### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded in cmp

### ISSUE THREAD

**Issue by NikolayBritavskiy** [Azeret/galIMF#2]
I would like to know how to solve the next error which is appeared even with the test input parameters on 1023 line of the code: 

RuntimeError: maximum recursion depth exceeded in cmp

I adopted SFR=3e-4; [F/H]=-1

Thank you an advance!

**Comment by juzikong** [comment]
Dear Britvaskiy,

We check the code with different computers but do not see the error.
Please check first that you are using the newest version of Python 3 instead of Python 2.
More information regards to the deployment can be found [here](https://github.com/Azeret/galIMF#deployment).
Please contact again if there is still this error.

We thank you for your report and best regards,
Yan & Tereza

**Comment by NikolayBritavskiy** [comment]
Thank you very much, indeed the problem was in an old version of Python.
